services:
  api:
    build: .
    container_name: nest-js-api
    restart: always
    depends_on:
      - db
    env_file:
      - .env                 
    ports:
      - "${PORT}:6000"       
    command: npm run start:prod

  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env                 
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "18000:8080"
    depends_on:
      - db

volumes:
  postgres_data:
