services:
  # NestJS API Service (Development)
  api:
    build: .
    restart: always
    ports:
      - '6000:3000'
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=myuser
      - DB_PASSWORD=mypassword
      - DB_DATABASE=mydatabase
      - JWT_SECRET=your-jwt-secret-key
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '15432:5432'

  # Database Admin Interface
  adminer:
    image: adminer
    restart: always
    ports:
      - '18000:8080'
    depends_on:
      - db

volumes:
  postgres_data:
